
  axio_dev: [  # The axiomatic device controller(s). An axiomatic is a CAN device that controls a set of analog/digital input output pins for reading sensor values and driving outputs. 
    {
      name: "Axiomatic_1",                         # The name of the device.
      eds_file: "./config/EDS-23123-1.01.eds",    # The path and name of the EDS file to use for this canopen evice. 
      dbc_file_name: "./config/axiomatic_23123-1.dbc",  # The dbc file should match the configuration of the RPDOs and TPDOs definied in the .EDS file otherwise the read data will have the wrong names and/or values.
      can_interface: "can0",                  # CAN Interface Number.
      can_interface_type: "socketcan",        # CAN Interface type to use.
      can_bitrate: 125000,                    # CAN bus baud rate in bps. Default factory setting is 125000 bps.
      can_max_read_timeout_ms: 100,           # The max time between checks on the CAN bus for new can messages.
      can_max_errors: 10,                     # The max number of read/wrtie errors before the CAN device is considered to be down. 
      write_period_ms: 100,                   # The period in milliseconds between writes to the device.

      display:
        {
          show_controls: ["clearFaults"],
        },
      default_control_inputs: {},
      device_id: 0x7F,                       # The CAN device ID. Also known as the canopen NODE_ID of the device.
      object_dict_config: [                  # Desired device values for the canopen object dictionary entries (this is only some of the canopen dict entries for the device, the ones we care about). The actual device is checked for the corresponding values to confirm the device is configured correctly and if not sets these values on the device.
        {
          name: "AI_Operating_mode", # 0x6112 Analog Input Pin modes,  0      Channel Off, 1      Normal Operation (analog), 10      Digital Input (On/Off), 20      Analog and On/Off
          subindicies: 
          [
            {
              subname: "Operating Mode Universal Input 1",
              value: 1,    # 1 = Analog Input Mode,
            },
            {
              subname: "Operating Mode Universal Input 2",
              value: 1,    # 1 = Analog Input Mode, 
            },
            {
              subname: "Operating Mode Universal Input 3",
              value: 1,    # 1 = Analog Input Mode, 
            },
            {
              subname: "Operating Mode Universal Input 4",
              value: 1,    # 1 = Analog Input Mode, 
            },
            {
              subname: "Operating Mode Universal Input 5",
              value: 1,    # 1 = Analog Input Mode,
            },
            {
              subname: "Operating Mode Universal Input 6", # 1 = Analog Input Mode, Pressure Sensor 1, voltage input
              value: 1,    
            },
            {
              subname: "Operating Mode Universal Input 7", 
              value: 1,     
            },
            {
              subname: "Operating Mode Universal Input 8", 
              value: 1,    
            },
            {
              subname: "Operating Mode Universal Input 9", # 1 = Analog Input Mode, Pressure Sensor 3, voltage input
              value: 1,
            },
            {
              subname: "Operating Mode Universal Input 10", # 1 = Analog Input Mode, Pressure Sensor 4, voltage input
              value: 1,
            },
            {
              subname: "Operating Mode Universal Input 11", # (Frequency Input)
              value: 1,     # 1 = Analog Input Mode
            },
            {
              subname: "Operating Mode Universal Input 12", # User selector switch has been set to OFF (Soft stop button)
              value: 1,
            },
          ]
        },
       {
          name: "DI Pullup/Down Mode 1 Input Line",  # Digital Input Pin Pull up/down resistor enabled on digital inputs.
          # 0: Disabled (High impedance)
          # 1: 22k Pullup Resistor Enabled (to 5v)
          # 2: 22k Pulldown Resistor Enabled (to GND)
          subindicies: 
          [
            {
              subname: 1,  
              value: 2,
            },
            {
              subname: 1,  
              value: 2,
            }
          ]
        },
        {
          name: "AI_Sensor_type",  # Analog Input Pin sensor mode selection. 40 Voltage Input, 50 Current Input, 60 Frequency Input (or RPM), 10000 PWM Input, 11000 Resistive Input
          subindicies: 
          [
            {
              subname: 1,
              value: 40,    # Sensor type is 40 for voltage input
            },
            {
              subname: 2,
              value: 40,    # Sensor type is 40 for voltage input
            },
            {
              subname: 3,
              value: 40,    # Sensor type is 40 for voltage input
            },
            {
              subname: 4,
              value: 40,    # Sensor type is 40 for voltage input
            },
            {
              subname: 5,
              value: 40,    # Sensor type is 40 for voltage input
            },
            {
              subname: 6,
              value: 40,     # Sensor type is 40 for voltage input
            },
            {
              subname: 8,
              value: 40,     # Sensor type is 40 for voltage input
            },
            {
              subname: 9,
              value: 40,     # Sensor type is 40 for voltage input
            },
            {
              subname: 10,
              value: 40,     # Sensor type is 40 for voltage input
            },
            {
              subname: 11,
              value: 60,     # Sensor type is 60 for frequency input
            },
            {
              subname: 12,
              value: 40,     # Sensor type is 40 for voltage input
            }
          ]
        },
        #TPDO 1 
        {
          name: "Transmit PDO Communication Parameter 0", # 0x1800      0x180 + Node ID = 0x7F
          subindicies: 
            [
              {
                subname: "COB ID", 
                value: 0x400001FF,    # 04000000h +  in the COB ID indicates that there is no RTR allowed on the PDO. 80000000h in the COB ID indicates that the PDO does not exist (destroyed).
              },
              {
                subname: "Transmission Type", 
                value: 0xFE, # transmission type 254 means, the application event is manufacturer specific (manufacturer specific part of the Object Dictionary) (it is published at the rate given by the Event Timer object)  
              },
              {
                subname: "Event Timer", 
                value: 100, # The rate to publish this tpdo can message in milliseconds.
              },
              {
                subname: "Inhibit Time",  # defines the minimum time that has to elapse between two consecutive invocations of a transmission service for that data object.
                value: 0,
              }
            ]     
        },
        {
          # TPDO1
          name: "Transmit PDO Mapping Parameter 0", # 0x1A00
          subindicies: 
            [
              {
                subname: "Number of entries", 
                value: 4,
              },
              {
                subname: 1,        # Can use the subindex name or the index value of the subindex in the Object Dict to define the subindex value.
                value: 0x71000110, # 0x71000110 is the object index 0x7100 with subindex 0x01, 0x10 = get 16 bits of this obj dict value of the first mapped object to place in TPDO CAN message. Analog input 1 FV
              },
              {
                subname: 2,
                value: 0x71000210, # 0x71000210 is the object index 0x7100 with subindex 0x02, 0x10 = get 16 bits of this obj dict value of the first mapped object to place in TPDO CAN message. Analog input 2 FV
              },
              {
                subname: 3,        # obj 7100h = AI Input Field Value (measured value of an analog input)
                value: 0x71000310, # 0x71000310 is the object index 0x7100 with subindex 0x03, 0x10 = get 16 bits of this obj dict value of the first mapped object to place in TPDO CAN message. Analog input 3 FV
              },
              {
                subname: 4,
                value: 0x71000410, # 0x71000410 is the object index 0x7100 with subindex 0x04, 0x10 = get 16 bits of this obj dict value of the first mapped object to place in TPDO CAN message. Analog input 4 FV
              }
            ]     
        },
        # TPDO2 communication parameters 
        {
          name: "Transmit PDO Communication Parameter 1", # 0x1801    0x180 + Node ID = 0x7F
          subindicies: 
            [
              {
                subname: "COB ID", 
                value: 0x400002FF,    # 04000000h +  in the COB ID indicates that there is no RTR allowed on the PDO. 80000000h in the COB ID indicates that the PDO does not exist (destroyed).
              },
              {
                subname: "Transmission Type", 
                value: 0xFE, # transmission type 254 means, the application event is manufacturer specific (manufacturer specific part of the Object Dictionary) (it is published at the rate given by the Event Timer object)  
              },
              {
                subname: "Event Timer", 
                value: 100, # The rate to publish this tpdo can message in milliseconds.
              },
              {
                subname: "Inhibit Time",  # defines the minimum time that has to elapse between two consecutive invocations of a transmission service for that data object.
                value: 0,
              }
            ]     
        },
        {
          # TPDO2 mapping parameters
          name: "Transmit PDO Mapping Parameter 1", # 0x1A01 
          # Sensor 1 = input 6, Sensor 2 = input 8, Sensor 3 = input 9, Sensor 4 = input 10
          subindicies: 
            [
              {
                subname: "Number of entries", 
                value: 4,
              },
              {
                subname: 1, # Analog input 5
                value: 0x71000510, # 0x71000510 is the object index 0x7100 with subindex 0x05, 0x10 = get 16 bits of this obj dict value. Analog input 5 FV
              },
              {
                subname: 2, # Analog input 6
                value: 0x71000610, # 0x71000610 is the object index 0x7100 with subindex 0x06, 0x10 = get 16 bits of this obj dict value. Analog input 6 FV
              },
              {
                subname: 3, # Analog input 7
                value: 0x71000710, # 0x71000710 is the object index 0x7100 with subindex 0x07, 0x10 = get 16 bits of this obj dict value. Analog input 7 FV
              },
              {
                subname: 4, # Analog input 8
                value: 0x71000810, # 0x71000810 is the object index 0x7100 with subindex 0x08, 0x10 = get 16 bits of this obj dict value. Analog input 8 FV
              },
            ]     
        },


        # TPDO3 communication parameters
        {
          name: "Transmit PDO Communication Parameter 2", #  0x1802     0x380 + Node ID = 0x7F
          subindicies: 
            [
              {
                subname: "COB ID", 
                value: 0x400003FF,    # 04000000h +  in the COB ID indicates that there is no RTR allowed on the PDO. 80000000h in the COB ID indicates that the PDO does not exist (destroyed).
              },
              {
                subname: "Transmission Type", 
                value: 0xFE, # transmission type 254 means, the application event is manufacturer specific (manufacturer specific part of the Object Dictionary) (it is published at the rate given by the Event Timer object)  
              },
              {
                subname: "Event Timer", 
                value: 100, # The rate to publish this tpdo can message in milliseconds.
              },
              {
                subname: "Inhibit Time",  # defines the minimum time that has to elapse between two consecutive invocations of a transmission service for that data object.
                value: 0,
              }
            ]     
        },
        {
          # TPDO3 mapping parameters
          name: "Transmit PDO Mapping Parameter 2", # 0x1A02
          subindicies: 
            [
              {
                subname: "Number of entries", 
                value: 4,
              },
              {
                subname: 1, # Analog input 9
                value: 0x71000910, # 0x71000910 is the object index 0x7100 with subindex 0x09, 0x10 = get 16 bits of this obj dict value. Analog input 9 FV
              },
              {
                subname: 2, # Analog input 10
                value: 0x71000A10, # 0x71000A10 is the object index 0x7100 with subindex 0x0A, 0x10 = get 16 bits of this obj dict value. Analog input 10 FV
              },
              {
                subname: 3, # Analog input 11
                value: 0x71000B10, # 0x71000B10 is the object index 0x7100 with subindex 0x0B, 0x10 = get 16 bits of this obj dict value. Analog input 11 FV
              },
              {
                subname: 4, # Analog input 12
                value: 0x71000C10, # 0x71000C10 is the object index 0x7100 with subindex 0x0C, 0x10 = get 16 bits of this obj dict value. Analog input 12 FV
              },
            ]     
        },
      ]
    },
  ]

